-- Austin FloodOps durable ledger.
-- Apply in a dedicated Supabase project. The server uses the service-role key;
-- never expose that key to the browser. SQLite remains the offline replay store.

create table if not exists public.events (
  event_id text primary key,
  observed_at timestamptz not null,
  source text not null,
  payload jsonb not null
);

create table if not exists public.decisions (
  incident_id text primary key,
  created_at timestamptz not null,
  payload jsonb not null
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  incident_id text not null,
  created_at timestamptz not null default now(),
  correction text not null,
  outcome text not null
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  rule text not null,
  source_incident_id text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.deliveries (
  incident_id text not null,
  channel text not null,
  delivered_at timestamptz not null default now(),
  response_status integer not null,
  primary key (incident_id, channel)
);

create index if not exists events_observed_at_idx on public.events (observed_at desc);
create index if not exists decisions_created_at_idx on public.decisions (created_at desc);

alter table public.events enable row level security;
alter table public.decisions enable row level security;
alter table public.feedback enable row level security;
alter table public.memories enable row level security;
alter table public.deliveries enable row level security;

-- No browser policy is granted. Server-side service-role access bypasses RLS;
-- a future authenticated operator UI should receive explicit read policies.
